name: 'Notify Teams Channel'
author: 'Kulbhushan Mayer'
description: 'It will send the message in MS Teams channel about the status of Job'
inputs: 
  webhook_uri:
    description: 'Webhook URL for the MS Teams Channel to receive the Message'
    required: true
  message:
    description: "Message to be posted in MS Teams Channel"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.webhook_uri }}
    - ${{ inputs.message }}